---
- name: Install httpd
  dnf:
    name: "{{ httpd_package }}"
    state: present
    use_backend: dnf5  # You can change this to dnf4 if needed

- name: Install apr-util-pgsql
  dnf:
    name: apr-util-pgsql
    state: present
    use_backend: dnf5

- name: Install apr-util-openssl
  dnf:
    name: apr-util-openssl
    state: present
    use_backend: dnf5

- name: Install mod_session
  dnf:
    name: mod_session
    state: present
    use_backend: dnf5

- name: Ensure httpd.conf is present
  template:
    src: httpd.conf.j2
    dest: /etc/httpd/conf/httpd.conf
    owner: root
    group: root
    mode: '0644'
  when: ansible_os_family == "RedHat"

- name: Copy autoindex.conf
  copy:
    src: autoindex.conf
    dest: /etc/httpd/conf.d/autoindex.conf
    owner: root
    group: root
    mode: '0644'

- name: Enable and start httpd service
  service:
    name: "{{ httpd_service }}"
    state: started
    enabled: yes
