- name: Install Nginx in Ubuntu
  apt:
    name: nginx
    state: present
  when: ansible_os_family == 'Debian'

- name: Install Nginx in Amazon Linux
  yum:
    name: nginx
    state: present
  when: ansible_os_family == 'RedHat'
