---
- name: Restart httpd service
  service:
    name: httpd
    state: restarted
  become: True

- name: Reload httpd
  service:
    name: httpd
    state: reloaded
  become: True

- name: Reload Apache
  service:
    name: apache2
    state: reloaded