    - name: Install mod_ssl package
      yum:
        name: mod_ssl
        state: present

    - name: Configure SSL template
      template:
        src: ssl.conf.j2
        dest: /etc/httpd/conf/ssl.conf
        owner: root
        group: root
        mode: '0644'
      notify: Reload httpd

    - name: Copy SSL configuration file
      copy:
        src: httpd_ssl.conf.j2
        dest: /etc/httpd/conf.d/ssl.conf
        owner: root
        group: root
        mode: '0644'
      notify: Reload httpd

    - name: Copy private keys
      copy:
        src: "{{ item }}"
        dest: "/etc/pki/tls/private/{{ item }}"
        owner: root
        group: root
        mode: '0600'
      with_items: "{{ mm_httpd.keys }}"
      notify: Reload httpd

    - name: Copy certificates
      copy:
        src: "{{ item }}"
        dest: "/etc/pki/tls/certs/{{ item }}"
        owner: root
        group: root
        mode: '0644'
      with_items: "{{ mm_httpd.certificates }}"
      notify: Reload httpd