---
- name: Update yum cache
  yum:
    name: "*"
    state: latest
    update_cache: yes

- name: Install Apache HTTPD
  yum:
    name: httpd
    state: present

- name: Start and enable httpd service
  service:
    name: httpd
    state: started
    enabled: yes
