    - name: Update package list
      apt:
        update_cache: yes
    - name: Install python3.9
      apt:
        name: python3.9
        state: present

    - name: Install Apache and required packages
      apt:
        name:
          - apache2
          - libaprutil1-dbd-pgsql
          - libssl-dev
        state: present

    - name: Enable Apache modules
      command: a2enmod ssl session ldap

    # - name: Ensure Apache configuration file is present
    #   template:
    #     src: ubuntu-httpd.conf.j2
    #     dest: /etc/apache2/apache2.conf
    #     owner: root
    #     group: root
    #     mode: '0644'
      # when: ansible_os_family == "Debian"

    # - name: Enable and start Apache service
    #   service:
    #     name: apache2
    #     enabled: yes
    #     state: started